spring:
  profiles:
    active: dev
---
# 개발 서버 설정
spring:
  config:
    activate:
      on-profile: dev

# 데이터베이스 설정
  datasource:
    driverClassName : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://192.168.0.2:3306/demo
    username: demo
    password: demo
  messages:
    basename: errors
server:
  port: 8082

---
# 실제 서버 설정
spring:
  config:
    activate:
      on-profile: real

  # 데이터베이스 설정
#  datasource:
#    driverClassName: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://182.208.254.170:3306/plasma
#    username: plasma
#    password: plasma@admin

server:
  port: 10010
---

# Mybatis 설정
mybatis:
  # mybatis 매핑 type을 짧게 쓰기 위한 설정
  type-aliases-package: com.example.demo.vo, com.example.demo.form ,com.example.demo.util
  # mapper.xml 위치 지정
  mapper-locations: mappers/**/*.xml
  configuration:
    # under score 를 camel case 로 변환
    map-underscore-to-camel-case: true
    # 한 개의 구문에서 여러 개의 ResultSet 을 허용
    multiple-result-sets-enabled: true
    # 쿼리 결과 필드가 null인 경우, 누락이 되서 나오는데 누락이 안되게 하는 설정
    call-setters-on-nulls: true

# Thymeleaf 설정
spring:
  thymeleaf:
    # thymeleaf에 대한 캐시를 남기지 않는다. cache=false 설정(운영시는 true)
    cache: false
    # templates 디렉토리에 파일이 있는지 없는지 체크, 없으면 에러를 발생시킨다.
    check-template-location: true
    order: 0
    prefix: classpath:/templates/
    suffix: .html

  # 정적 리소스 경로
  web:
    resources:
      static-locations: classpath:/static/assets/
      # 캐시 유효기간 1년
      cache:
        cachecontrol:
          max-age: 31536000
          version: 2021-08-09

      #  Fixed Version Strategy
      chain:
        cache: true

  # 정적 리소스에 변화가 있을 때 바로 반영한다.
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      # total file size cannot exceed 10MB.
      max-file-size: 10MB
      # total request size for a multipart/form-data cannot exceed 20MB.
      max-request-size: 20MB

# 로그 설정
logging:
  level:
    com.example.demo : debug
    jdbc: off
    jdbc.audit: off
    jdbc.resultset : off
    jdbc.connection: off
    jdbc.sqltiming: info
    jdbc.resultsettable: info
  file:
    path: D:/logs/demo.log

# mail 설정
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: koko5793@gmail.com
  password: dlsgkr21
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true

# session 설정
  server:
    servlet:
      session:
        timeout: 60m

# paging 설정
#pagehelper:
#  # 사용할 DB 설정
#  helper-dialect: mariadb
#  # 범위를 넘어가는 pageNum가 들어올 때 가능할 값으로 변경
#  reasonable: true

# 파일 경로
custom:
  path:
    upload-images: 'D:/dev/upload-images/'

resources:
  location: D:/upload/@project.name@
  uri_path: /upload/@project.name@/**



file:
  downloadPath: D:/upload/@project.name@/
  thumbnailPath: D:/upload/@project.name@/thumbnail/

# 사이트명 -> 이메일에 사이트명 첨부
site:
  name: 사이트명테스트
# 페이징 처리
pageCount:
  mobile: 5
  web: 10


# 게시판 컨텐츠 개수
contentCount:
  # 일반 게시판
  basic:
    mobile: 10
    web: 10
  # 포토 게시판
  photo:
    mobile: 10
    web: 12

